server:
  port: 8094
  servlet:
    context-path: /LoadFile

spring:
  application:
    name: LoadFile
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlserver://192.168.0.61;databaseName=LoadFile;encrypt=false;integratedSecurity=false;
    username: giovanni.andrade
    password: gigi1704

config:
  rootPath: D:\loadFileData\
  downloadPath: /home/selenium/Downloads
  dockerPathDownload: http://192.168.0.104:8094/LoadFile/downloads/