package br.com.certacon.certabotloadfiles.utils;

public enum StatusFile {
    OK, CREATED, ERROR, UPDATED, UPLOADED, MOVED, UNZIPPED, READY, CREATEDPATH, CREATEDSENT, CREATEDARCHIVED, CREATEDORGANIZE, CREATEDORGANIZED, ZIPPED
}
